version: "3.9"

services:
  app:
    image: node:24-alpine
    container_name: app_dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/flowers-care
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowers-care
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: