services:
  app:
    image: node:24-alpine
    container_name: app_dev
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:delegated
      - ./node_modules:/usr/src/app/node_modules
    command: sh -c "yarn install && yarn start:dev"
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - application

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks:
      - application

volumes:
  postgres_data:

networks:
  application:
    name: flowers-care
    external: false